package me.chasertw123.villagedefense.stats;

public enum Stat {

    MOBKILLS, DEATHS, GAMESPLAYED, WAVESPLAYED, WAVESWON, WAVESLOST, TOTALEXPERIENCEEARNED, TOTALGOLDEARNED, TOTALGOLDSPENT;

}
